name: pet_adoption_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  intl: ^0.19.0
  firebase_storage: ^11.0.16
  image_picker: ^1.0.7
  fluttertoast: ^8.2.4
  font_awesome_flutter: ^10.6.0
  jiffy: ^6.2.1
  flutter_riverpod: ^2.4.9
  flutter_holo_date_picker: ^1.1.3
  provider: ^6.1.1
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
  - images/image1.png
  - images/image2.jpg
  - images/image3.jpg
  - images/image4.jpg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
